### ISSUE TITLE
lr6603.tis

### ISSUE THREAD

**Issue by ALIENQuake** [InfinityMods/LongerRoadEE#1]
@RoxanneSHS Does this fix is needed http://www.shsforums.net/topic/22248-fix-for-the-game-crashing-bug-when-teleporting-to-elysium/ ?

**Comment by RoxanneSHS** [comment]
No.
The tis/tiz files or the original have been replaced by Tis/PVRZ for the EE. I have encountered no issue with the new map graphics in my tests.

See changelog entry
- remove tiz/tis conversion and use PVRZ
