### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by RoxanneSHS** [InfinityMods/LongerRoadEE#2]
This mod version is outdated
Current compatible version is 1.8

**Comment by GregCampbellPresents** [comment]
How to get the latest version?

**Comment by RoxanneSHS** [comment]
There is only one for EE games https://github.com/RoxanneSHS/LongerRoadEE/archive/1.8.zip
For classic games the mod is no longer compatible with the updated Ascension and SCS mods.

**Comment by ALIENQuake** [comment]
As of 2.0.0, this is no longer true.
