### ISSUE TITLE
Error in LongerRoad.tp2

### ISSUE THREAD

**Issue by DATACKO** [InfinityMods/LongerRoadEE#3]
Installation stopps in EE-Versions because of an error in LongerRoad.tp2 at line 58.
Code is:
COPY ~LongerRoadmp/ee~		~override~

Code should be:
COPY ~LongerRoad/bmp/ee~		~override~

**Comment by ALIENQuake** [comment]
@DATACKO Hi, thanks for the report and sorry for the late reaction. No idea how this could slip through 😉 Fixed by https://github.com/InfinityMods/LongerRoadEE/releases/tag/2.0.1
