### ISSUE TITLE
Typos, missing Res and BCS

### ISSUE THREAD

**Issue by TotoR115** [InfinityMods/LongerRoadEE#4]
In **lrdeva.d** there is a Typo:

https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/dlg/lrdeva.d#L5
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/dlg/lrdeva.d#L6

Should be `HaerDalis` instead of `Haer'Dalis`

In **CESPEN.BCS:**
`L33: 		ApplySpell("runrun",0)`
should be:
`L33: 		ApplySpellRes("runrun",Myself)`

This typo is already fixed in BG2fixpack. 

For more compatibility, it seems that LR mod should avoid overriding existing script and `APPEND` them instead.

**Comment by TotoR115** [comment]
After looking a little bit more in that, there are some more for compatibility.

**BCS** (from direct copy):
- FINBODHI.BCS override the original script
- ITHEADS.BCS override the original script
both overriding could be avoid with `EXTEND_BOTTOM` or `REPLACE_BCS_BLOCK`

**ITM** (from direct copy):
- finipotn.itm
- finir0m.itm
- finir0r.itm
- finirobe.itm
- irenbrch.itm
- irenprce.itm
overriding could be avoid by using `FILE_EXISTS_IN_GAME`

**Missing Res**
`finirat.cre` is copyed without its script making it useless... `finirat.bcs` is missing

**typos**:
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L483
even if harmless there is a space after `fresienne`

 **overview 01**:
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L829-L833
this part seems to need a check for EE, if it is only for EE

 **overview 02**:
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L797-L798
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L818
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L820-L827
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L835-L838
those lines should not be inside ascenssion compatibility check, it is independant

**Res**:
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L581
https://github.com/InfinityMods/LongerRoadEE/blob/db7253e7269e182817023096b7b6cad8d7cc166f/LongerRoad/LongerRoad.tp2#L587
the Quote (//) could be removed for both as the RES exists in bmp

**Comment by TotoR115** [comment]
Some bam files have transparency issues: 

- BASS1.BAM
- dspark2.bam
- SESS1.BAM

updated vesion could be find here: https://drive.google.com/drive/folders/11UHIIxGQuMmkyetp8ttJkaTwW1HZBiDl?usp=sharing

**Comment by ALIENQuake** [comment]
Thanks for this, I will make an update when I have a moment.

**Comment by TotoR115** [comment]
if you want I could make a Pull Request with all those little bugs

**Comment by ALIENQuake** [comment]
Sure!

**Comment by ALIENQuake** [comment]
Closed by #5
