### ISSUE TITLE
Broken fonts

### ISSUE THREAD

**Issue by Vazirazi** [InfinityMods/LongerRoadEE#7]
Hey I have installed mod in Polish langugage. And there is no text, only rectangles.
![image](https://github.com/InfinityMods/LongerRoadEE/assets/23178479/fbd8d6bd-54af-429e-be01-78a8d9073429)

**Comment by ALIENQuake** [comment]
@Vazirazi Hi, cannot reproduce:
oBG2: https://i.imgur.com/dFSxW26.jpeg
BG2EE: https://i.imgur.com/kJKXK4T.jpeg
please try a clean installation of the game and the mod itself.

**Comment by Vazirazi** [comment]
Thanks, after reinstallation full game, it is working now.
