### ISSUE TITLE
No exe file in zip

### ISSUE THREAD

**Issue by Vazirazi** [InfinityMods/LongerRoadEE#8]
There is no exe file in zip. Had to download from other source:

https://www.gibberlings3.net/forums/topic/32127-the-longer-road-200-combined-release-for-vanilla-and-ee-version/

**Comment by ALIENQuake** [comment]
The 'Download' section for all 'github things' is here: https://github.com/InfinityMods/LongerRoadEE/releases/latest and the 'other source' from you link is using the files from 'GitHub Releases'.
