### ISSUE TITLE
Final fight and encoding

### ISSUE THREAD

**Issue by TotoR115** [InfinityMods/LongerRoadEE#9]
See:https://www.gibberlings3.net/forums/topic/37283-lurkers-eet-install-eet-modpack_2023-09-17_v1-was-passive-black-talons/#comment-329223

Bugs: 
- Final fight not triggering
- bad tra file encoding

**Comment by TotoR115** [comment]
@ALIENQuake 

> Final fight not triggering

should be solve with #10

> bad tra file encoding

I was not able to reproduce this bug

**Comment by ALIENQuake** [comment]
@TotoR115 I've found malformed English texts, and will try to correct this.

**Comment by TotoR115** [comment]
Thank you, 
So I let you do the versioning 😉
